language: node_js

node_js:
  - "8"
  - "10"

cache:
  directories:
    - "node_modules"

before_script:
  - |
    if [[ $(node -v) == v10* ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
      ./cc-test-reporter before-build
    fi

script:
  - npm run lint
  - npm run test:coverage

after_script:
- |
  if [[ $(node -v) == v10* ]]; then
    ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  fi
